<?php

return [
    'max_image_size'    => 50000,
    'max_file_size'     => 50000,
    'max_width'         => 3000,
    'max_height'        => 3000,

    'mimetypes'         => [
        'application/msword',
        'application/octet-stream',
        'application/pdf',
        'application/rtf',
        'application/vnd',
        'application/vnd.ms-excel',
        'application/vnd.ms-office',
        'application/vnd.ms-powerpoint',
        'application/vnd.oasis.opendocument.text',
        'application/vnd.openxmlformats-officedocument.presentationml.presentation',
        'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
        'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
        'application/x-compressed',
        'application/x-rar-compressed',
        'application/x-zip-compressed',
        'application/zip',
        'audio/mp3',
        'audio/mp4',
        'audio/mpeg',
        'audio/ogg',
        'image/gif',
        'image/jpeg',
        'image/pjpeg',
        'image/png',
        'image/svg+xml',
        'image/webp',
        'multipart/x-zip',
        'text/css',
        'text/html',
        'text/plain',
        'text/xml',
        'video/mp4',
        'video/ogg',
        'video/webm',
        'video/x-flv',
        'video/x-m4v',
        'video/x-ms-wmv',
        'video/x-msvideo',
    ],
];
